/home/rq2/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<wipe_dms() done, defined at /home/rq2/cs213bot/cs213bot/cs213bot.py:79> exception=TypeError("'HistoryIterator' object is not an iterator")>
Traceback (most recent call last):
  File "/home/rq2/cs213bot/cs213bot/cs213bot.py", line 87, in wipe_dms
    if msg := next(channel.history(limit=1), None):
TypeError: 'HistoryIterator' object is not an iterator
Task exception was never retrieved
future: <Task finished name='Task-797' coro=<wipe_dms() done, defined at /home/rq2/cs213bot/cs213bot/cs213bot.py:79> exception=TypeError("'HistoryIterator' object is not an iterator")>
Traceback (most recent call last):
  File "/home/rq2/cs213bot/cs213bot/cs213bot.py", line 87, in wipe_dms
    if msg := next(channel.history(limit=1), None):
TypeError: 'HistoryIterator' object is not an iterator
Task exception was never retrieved
future: <Task finished name='Task-928' coro=<wipe_dms() done, defined at /home/rq2/cs213bot/cs213bot/cs213bot.py:79> exception=TypeError("'HistoryIterator' object is not an iterator")>
Traceback (most recent call last):
  File "/home/rq2/cs213bot/cs213bot/cs213bot.py", line 87, in wipe_dms
    if msg := next(channel.history(limit=1), None):
TypeError: 'HistoryIterator' object is not an iterator
Task exception was never retrieved
future: <Task finished name='Task-1148' coro=<wipe_dms() done, defined at /home/rq2/cs213bot/cs213bot/cs213bot.py:79> exception=TypeError("'HistoryIterator' object is not an iterator")>
Traceback (most recent call last):
  File "/home/rq2/cs213bot/cs213bot/cs213bot.py", line 87, in wipe_dms
    if msg := next(channel.history(limit=1), None):
TypeError: 'HistoryIterator' object is not an iterator
fatal: could not read Username for 'https://github.com': No such device or address
fatal: could not read Username for 'https://github.com': No such device or address
tools.py module loaded
meta.py module loaded
commands.py module loaded
sm213.py module loaded
Logged in successfully
Logged in successfully
Logged in successfully
Logged in successfully
